#!/usr/bin/env python3
"""Verify private inputs, prepare pinned dependencies and build the real Android port.

No ROM download, stub engine, remote upload, Git push, or automatic SDK-license
acceptance is performed. --prepare-only prepares sources without invoking the Android build.
"""
from __future__ import annotations
import argparse
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import uuid

BASE = "cb4dae77a6552790cbb7a9663957b2cb6c3e6b58"
ENGINE = "851b11e38588818afc705e4270d3eb982b7b2af2"
SDL = "c98c4fbff6d8f3016a3ce6685bf8f43433c3efcc"
ROM_SHA = "fa8cacf5bbfc39ee6bbaa557adf89133d60d42f6cf9e1db30d5a36a469f74d15"
ROM_SIZE = 4194304
NDK = "28.2.13676358"
ROOT = Path(__file__).resolve().parents[2]


def run(args: list[str], *, cwd: Path | None = None, capture: bool = False) -> str:
    p = subprocess.run(args, cwd=ROOT if cwd is None else cwd, text=True, check=True,
                       stdout=subprocess.PIPE if capture else None)
    return p.stdout.strip() if capture else ""


def strip_copier_header(raw: bytes) -> bytes:
    if len(raw) == ROM_SIZE + 512:
        return raw[512:]
    if len(raw) != ROM_SIZE:
        raise ValueError("ROM: se esperan 4 MiB, con o sin cabecera de 512 bytes. No ZIP.")
    return raw


def read_rom(path: Path) -> bytes:
    with path.open("rb") as stream:
        raw = stream.read(ROM_SIZE + 513)  # bound memory even for a huge/untrusted input
    payload = strip_copier_header(raw)
    actual = hashlib.sha256(payload).hexdigest()
    if actual != ROM_SHA:
        raise ValueError(f"ROM no compatible: SHA-256 {actual}; se exige USA v1.0 ({ROM_SHA}).")
    return payload


def check_repository(allow_changes: bool) -> None:
    for path in ["CMakeLists.txt", "scripts/generate_snesrecomp.py", "runner/dkc1_game.c"]:
        if not (ROOT / path).is_file():
            raise RuntimeError("Este paquete es una capa para el fork, no una copia del juego. "
                               "Ejecuta APLICAR_PORT.py desde el paquete original.")
    run(["git", "merge-base", "--is-ancestor", BASE, "HEAD"])
    # Android-only commits are fine. Refuse silent changes to audited game inputs.
    paths = ["runner", "recomp", "scripts", "CMakeLists.txt", ".gitmodules",
             ":(exclude)recomp/funcs.h"]  # regenerated by the upstream header synchronizer
    changed = run(["git", "diff", "--name-only", BASE, "--", *paths], capture=True)
    if changed and not allow_changes:
        raise RuntimeError("Hay cambios al núcleo revisado. No se sobrescriben:\n" + changed +
                           "\nRevisa esos cambios y usa --allow-source-changes explícitamente.")


def checkout_sdl(destination: Path) -> None:
    if destination.exists():
        head = run(["git", "rev-parse", "HEAD"], cwd=destination, capture=True)
        dirty = run(["git", "status", "--porcelain", "--untracked-files=no"], cwd=destination, capture=True)
        if head != SDL or dirty:
            raise RuntimeError("El SDL2 existente no coincide o tiene cambios. No se modifica.")
        return
    destination.parent.mkdir(parents=True, exist_ok=True)
    stage = destination.with_name("SDL2-stage-" + uuid.uuid4().hex)
    stage.mkdir()
    try:
        run(["git", "init"], cwd=stage)
        run(["git", "remote", "add", "origin", "https://github.com/libsdl-org/SDL.git"], cwd=stage)
        run(["git", "fetch", "--depth", "1", "origin", SDL], cwd=stage)
        run(["git", "checkout", "--detach", "FETCH_HEAD"], cwd=stage)
        stage.rename(destination)
    except Exception:
        # Only remove the new directory created by this call, never an existing checkout.
        shutil.rmtree(stage, ignore_errors=True)
        raise


def prepare_dependencies() -> None:
    engine = ROOT / "snesrecomp"
    if (engine / "runner/runner.cmake").exists():
        if run(["git", "rev-parse", "HEAD"], cwd=engine, capture=True) != ENGINE:
            raise RuntimeError("El snesrecomp existente no coincide con el pin revisado. No se modifica.")
        if run(["git", "status", "--porcelain", "--untracked-files=no"], cwd=engine, capture=True):
            raise RuntimeError("El snesrecomp existente tiene cambios. No se modifica.")
    else:
        run(["git", "submodule", "update", "--init", "--recursive", "--depth", "1"])
    if run(["git", "rev-parse", "HEAD"], cwd=engine, capture=True) != ENGINE:
        raise RuntimeError("El submódulo snesrecomp no coincide con la revisión requerida.")
    checkout_sdl(ROOT / "android/third_party/SDL2")


def source_fingerprint() -> str:
    sha = hashlib.sha256()
    sources: list[Path] = []
    for name in ("runner", "recomp", "scripts"):
        sources += [p for p in (ROOT/name).rglob("*") if p.is_file() and p.suffix in (".c", ".h", ".cfg", ".py")]
    for path in sorted(sources):
        sha.update(path.relative_to(ROOT).as_posix().encode())
        sha.update(b"\0"); sha.update(path.read_bytes()); sha.update(b"\0")
    return sha.hexdigest()


def generated_files(directory: Path) -> dict[str, str]:
    return {p.name: hashlib.sha256(p.read_bytes()).hexdigest()
            for p in sorted(directory.glob("*")) if p.is_file() and p.suffix in (".c", ".h")}


def generate(payload: bytes, backend: str, regenerate: bool) -> None:
    directory = ROOT / "generated/snesrecomp"
    manifest = directory / "android-generation.json"
    desired = {"base": BASE, "engine": ENGINE, "rom_sha256": ROM_SHA, "backend": backend}
    fingerprint = source_fingerprint()
    if manifest.exists() and not regenerate:
        existing = json.loads(manifest.read_text())
        if all(existing.get(k) == v for k, v in desired.items()) and existing.get("inputs_sha256") == fingerprint \
                and existing.get("outputs") == generated_files(directory) and any(directory.glob("*.c")):
            print("Fuentes generadas verificadas; se reutilizan.")
            return
        raise RuntimeError("Fuentes generadas antiguas o modificadas. Usa --regenerate para regenerar con respaldo.")
    backup = None
    if directory.exists() and any(directory.iterdir()):
        if not regenerate:
            raise RuntimeError("Ya existen fuentes generadas sin un manifiesto Android válido. "
                               "Usa --regenerate; se conservará una copia antes de regenerar.")
        backup = directory.with_name("snesrecomp.backup-" + uuid.uuid4().hex)
        directory.rename(backup)
        print("Respaldo conservado:", backup)
    try:
        # The temporary clean ROM is private and OUTSIDE the Git worktree.
        with tempfile.TemporaryDirectory(prefix="dkc1-private-rom-") as temporary:
            rom = Path(temporary) / "dkc1.sfc"
            rom.write_bytes(payload)
            if os.name != "nt": rom.chmod(0o600)
            run([sys.executable, str(ROOT/"scripts/generate_snesrecomp.py"),
                 "--rom", str(rom), "--analysis-backend", backend])
        outputs = generated_files(directory)
        if not any(name.endswith(".c") for name in outputs):
            raise RuntimeError("El generador terminó sin fuentes C. No se construye un motor ficticio.")
        # Header synchronization can legitimately rewrite recomp/funcs.h.
        desired.update(inputs_sha256=source_fingerprint(), outputs=outputs)
        manifest.write_text(json.dumps(desired, indent=2) + "\n")
    except Exception:
        if backup is not None:
            if directory.exists(): directory.rename(directory.with_name("snesrecomp.failed-"+uuid.uuid4().hex))
            backup.rename(directory)
        raise


def check_sdk(sdk: Path) -> None:
    required = ["platforms/android-35/android.jar", "build-tools/35.0.0",
                f"ndk/{NDK}/build/cmake/android.toolchain.cmake", "cmake/3.22.1"]
    missing = [str(sdk/path) for path in required if not (sdk/path).exists()]
    if missing:
        raise RuntimeError("Faltan componentes del SDK:\n" + "\n".join(missing) +
            '\nInstálalos desde Android Studio o sdkmanager: "platforms;android-35" '
            '"build-tools;35.0.0" "cmake;3.22.1" "ndk;'+NDK+'". Revisa y acepta sus licencias.')
    if not shutil.which("java"):
        raise RuntimeError("Falta Java. Configura JDK 17 (JAVA_HOME y PATH).")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--rom", type=Path, required=True)
    p.add_argument("--sdk", type=Path)
    p.add_argument("--prepare-only", action="store_true")
    p.add_argument("--verify-only", action="store_true")
    p.add_argument("--regenerate", action="store_true")
    p.add_argument("--allow-source-changes", action="store_true")
    p.add_argument("--backend", choices=["python", "native"], default="python")
    args = p.parse_args()
    payload = read_rom(args.rom.expanduser())
    print("ROM USA v1.0 verificada. No se subirá ni incluirá en el APK.")
    if args.verify_only: return 0
    sdk = args.sdk or (Path(os.environ["ANDROID_HOME"]) if os.environ.get("ANDROID_HOME") else
                       Path(os.environ["ANDROID_SDK_ROOT"]) if os.environ.get("ANDROID_SDK_ROOT") else None)
    if not args.prepare_only:
        if sdk is None: raise RuntimeError("Indica --sdk <directorio> o configura ANDROID_HOME.")
        sdk = sdk.expanduser().resolve();check_sdk(sdk)
        os.environ["ANDROID_HOME"] = str(sdk)
    if not shutil.which("git"): raise RuntimeError("Git no está instalado o no está en PATH.")
    check_repository(args.allow_source_changes)
    prepare_dependencies()
    generate(payload, args.backend, args.regenerate)
    del payload
    if args.prepare_only:
        print("Preparación terminada. Instala el SDK indicado y repite sin --prepare-only. Aún no hay APK.")
        return 0
    run([sys.executable, str(ROOT/"android/tools/gradle_runner.py"),
         "--no-daemon", ":app:assembleDebug"], cwd=ROOT/"android")
    apk = ROOT / "android/app/build/outputs/apk/debug/app-debug.apk"
    if not apk.is_file(): raise RuntimeError("Gradle no produjo el APK esperado.")
    print("APK construido (todavía requiere pruebas en un teléfono):", apk)
    print("SHA-256:", hashlib.sha256(apk.read_bytes()).hexdigest())
    return 0

if __name__ == "__main__":
    try: raise SystemExit(main())
    except (OSError, ValueError, RuntimeError, subprocess.CalledProcessError) as error:
        print("ERROR:", error, file=sys.stderr);raise SystemExit(1)
